# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: New Jupyter-Book Template
author: Nigel Nighthawk
logo: UNG.logo.png

# Allow re-execution of notebooks as needed on each build.
# Dramatically improves compile speeds since only changed files recompile each time.
# The jupyterbook document suggests 'force', but I do not.
# See https://jupyterbook.org/content/execute.html

execute:
  execute_notebooks: 'auto'

# Allows full access to MYST Markdown features
# For an overview of MYST, see https://jupyterbook.org/content/myst.html 

parse:
  myst_extended_syntax: true  

# Information about where the book exists on the web
#repository:
#  url: https://github.com/nigel/nighthawk  # Online location of your book
#  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
#html:
#  use_issues_button: true
#  use_repository_button: true
